* HELP I NEED OUT
spam C-g
ESC ESC ESC
* help
C-h         Open help (q to quit)
C-h ?       I am losttttt
C-h i       Go to Info
C-h r       Go to Manual
C-h [char] Various help info
C-h c [command/seq] - short help w command
C-h k [command/seq] - long help w command
C-h v       Info on variable
C-h f       Info on function
C-h a       Search commands (fuzzy)
C-h d       Search DOCS (fuzzy)
C-h r i     Search indexes of Emacs manual, present first match
C-h r s     Search TEXT of manual
C-h c-f     Display Emacs faq

** help/manual commands
?          Show all commands
space      Keep going forward
del        Go back
n          Next node
p          Prev node
b          Beginning of node
^          Up from node
]          Next (flattened) node
[          Prev (flattened) node
m          Go to menu item
u          Up a node
* commands
C-x + [character] - for frequently used commands
M-x + [words] - for less frequent commands
* copy/paste
C-w        Kill (cut)
M-w        kill-ring-save (copy)
C-y        yank (paste)
C-SPC      set mark (+c-w to kill)
M-y        cycle thru kill buffer
C-/        undo (works for delete)
C-/,        any command, C-/ Redo
* text editor navigation
C-f         Move forward a character
C-b         Move backward a character
M-f         Move forward a word
M-b         Move backward a word
C-n         Move to next line
C-p         Move to previous line
C-a         Move to beginning of line
C-e         Move to end of line
M-a         Move back to beginning of sentence
M-e         Move forward to end of sentence
M-}         Move forward paragraph
M-{         Move back paragraph
C-v         View next screen
M-v         Previous screen
C-l         Center screen/shuffle
M-<         Move to beginning of text
M->         Move to end of text
M-g M-g     Goto line #
C-x C-x     Set mark, move to where it used to be ("move to other end of mark")
M-@         Set mark end of next work ("select word")
C-M-z       Set mark end of balanced exp (C-u for bckwd)
M-h         Mark curr paragraph
C-M-h       Mark current defun
C-x h       Mark buffer
C-x C-p     Mark page

* manipulating text
** deleting and killing text (take numeric arguments!)
C-d    Delete character after cursor
M-d    Delete word after cursor
C-k    Kill from cursor to EOL
M-k    Kill up to end of current sentence
** transposing (take numeric arguments!)
C-t    Transpose characters
M-t    Transpose words
C-x C-t Transpose line
C-M-t   Transpose expression
** case conversion
M-l    Lowercase (following word)
M-u    Uppercase (following)
M-c    First lettter capitalized (following)
** comments
C-x C-;  Comment out line
* search find replace
C-s          Forward Search (repeat to jump, del to go back,  return to term)
C-r          Reverse Search (return to term)
M-x replace-string <string to replace> <replace it with>
M-%      Shortcut for replace-string
C-space  Set mark (emacs often sets)
C-x C-x   Return to mark (return to prev)
C-u C-space Cycle mark
M-q            Enter query replace mode
            ! to replace all
            y to replace current
            n to go to next
            RET exit
C-c C-f     Find file at point (file imports in source code)
* window management
C-x 0     Close selected window, do NOT kill buffer
C-x 1     Close all windows EXCEPT selected
C-x 2     Window to bottom
C-x 3     Window to top
C-x } or { Shrink/Enlarge current window
C-x +     Balance windows in current frame
C-x 4 0   Delete selected window & kill its buffer
C-x 4 b <buffname> select buffer in other window
C-x 4 f <filename> open file other window
C-x 4 d <directory> open Dired in other window
C-x o      Move cursor to other window
C-M-v     Scroll other window down
C-M-S-v   Scroll other window up
C-M-S-l   Center other window
* frame management
C-x 5 2   Frame to right
C-x 5 0  Delete frame to right
* buffer management
C-x C-b  List buffers
C-x b [buffer]  Switch to buffer
C-x k [buffer]  Kill buffer
C-x right-arr   Move to next buffer
C-x left-arr    Move to prev buffer
* file management
C-x C-s    Save file
C-x s       Save open buffers
C-x C-f    Open or Create file (does not have to exist!)
C-x k       Close buffer
C-x d      Open dired
* dired
C-x C-q   Open/close 'edit' mode
d         Mark for deletion
u         Unmark
x         Delete marked files
* shell
M-x shell Opens a shell
* minibuffer
(M-x) M-p      Previous minibuffer history
(M-x) M-n      Next minibuffer history
(M-x) [REGEXP] Search
* emacs management
C-x C-c    Exit Emacs
C-z        Suspend Emacs
C-h m      View mode documentation
* prefix/meta arguments
C-u [number] [final command]       Repeat eg C-u 8 C-f
C-x z                              Repeat last command
* packages
List available packages?
      M-x list-packages
Package not found!!!!
      M-x package-refresh-contents
Install package
     Add to .emacs or
* file management
Recover file on crash?
      M-x recover-this-file [normal file]
* mode management
Toggle auto fill mode (break too wide lines)
      M-x auto-fill-mode
Toggle line wrap
      M-x toggle-truncate-lines               
* project management
    How can I register another project?
                M-x projectile-add-known-project
    How can I switch to another project?
                M-x projectile-switch-project
    How can I search for other files in this project?
                M-x projectile-find-file
    How can I do find-and-replace in this project?
                M-x projectile-replace
    How can I search for strings/words in this project?
                M-x projectile-grep or M-x projectile-ag or M-x projectile-rg (I recommend rg but it's seperate from emacs so you'll need to install it. If you don't want to bother with that, use projectile-grep, but grep is noticeably slow on larger projects).
** running code
M-x run-python   Start a python env
C-c C-c          Run current buffer in that (python) env
* code commands
M-x hs-minor-mode       Enable folding
C-c @ C-h               Hide current block
C-c @ C-s               Show current block
* Sections u have read
** Menu thru Killing
** missing middle
** Appendices thru Index (end)
